### PR TITLE
tests and changes for issue 640

### PR DESCRIPTION
**Pull request by uwej711**
See #640

### CODE REVIEW

**Comment by lsmith77** [comment]
```Doctrine\Tests\ODM\PHPCR\Mapping\ClassMetadataFactoryTest::testLoadMetadataClassInheritanceChildCanOverride`` seems to be failing

I guess we will put this into 1.3 only as it can maybe lead to some surprises .. its the bug fix type than can feel like a BC break ... right?

**Comment by uwej711** [comment]
Well it breaks BC but chances are only few people rely on the current behaviour.

**Comment by dbu** [comment]
the discussion is in #640 - i agree with considering this a bugfix with potential to break somebody relying on the bug.

@uwej711 do you want to add the replace-mixins attribute here or in a separate pull request?

**Comment by uwej711** [comment]
I would like to add it here ...

**Comment by dbu** [comment]
:+1:

**Comment by uwej711** [comment]
So I actually did this differently than I thought before, having mixins and replaceMixins in ClassMetadata would have made it necessary to change ClassMetadataFactory  and handling the replace logic there (which I now realize actually makes some sense). Maybe I will try that approach, too.

**Comment by dbu** [comment]
i like this implementation, imo we can merge as is. do you think the other aproach would be much better?

**Comment by uwej711** [comment]
The changes to this implementation I think about would move the check for mixins and replace-mixins from each driver to one implementation in ClassMetadata and the logic for overwriting the parent class' mixins should go to ClassMetadataFactory. These changes would reduce some redundancy and place the replace logic where the actual inheritance happens.

**Comment by uwej711** [comment]
closed in favour of #650

**Pull request closed without merging**
