### PR TITLE
Do not refresh session on UnitOfWork::clear()

### PR DESCRIPTION
**Pull request by pamil**
See discussion in doctrine/DoctrinePHPCRBundle#265.

###### Contains and resolves #731. Fixes doctrine/DoctrinePHPCRBundle#265.

### CODE REVIEW

**Comment by dantleech** [comment]
As mentioned in the [issue](https://github.com/doctrine/DoctrinePHPCRBundle/issues/265), I am not 100% sure this is the correct thing to do.

**Comment by pamil** [comment]
The ORM does not refresh entities on clear as well, so we may use the same pattern here.

Anyway, refreshing documents on clearing the `UnitOfWork` does not sound useful.

**Comment by pamil** [comment]
The Travis failure is not connected with this PR 😿

**Comment by dantleech** [comment]
@dbu @lsmith77 any idea why the session is refreshed when `UnitOfWork::clear` is called?

**Comment by pamil** [comment]
It was introduced in https://github.com/doctrine/phpcr-odm/commit/ce8fd9274875ef1e019bfaac1c5f9e931f7b1e7b, #67.

**Comment by pamil** [comment]
Rebased.

**Comment by dbu** [comment]
the difference is that the orm will do new sql queries when the object store is cleared. phpcr has an object model of nodes and properties that stays in memory even if we delete the odm objects. depending on the use case, one or the other is the correct thing to happen.

the stack trace in https://github.com/doctrine/DoctrinePHPCRBundle/issues/265 is a bug in jackalope - during refresh, it should only mark nodes as dirty so that they get reloaded from storage when accessed again. i created https://github.com/jackalope/jackalope/issues/321 about that.

while i think we could make a case for not discarding changes on phpcr level, i fear there is a BC break in this. people that expect it to happen would be confused. i think the best solution at this point is adding a flag to the DocumentManager::clear method whether to discard the phpcr session as well or not. something like `$refreshPhpcr = true`. in the place you call clear, you can specify false to get the behaviour you need.

**Comment by dantleech** [comment]
> phpcr has an object model of nodes and properties that stays in memory even if we delete the odm objects.

but at the ODM level - any changes in the UOW are not made on the PHPCR level until `flush()` is called. So clearing the UOW should not affect PHPCR at all? (?)

**Comment by dbu** [comment]
question is whether you want to clear to just discard your changes or also to see changes that happened at the backend since you did your thing. e.g. a recovery code after an exception during flush that something got deleted at the backend - if you clear and try again, phpcr-odm will still see the outdated phpcr nodes and things wont be fixed...

we can discuss changing the default behaviour for clear(), but i would keep both modes. and to fix the issue at hand, having at least an option to tell not to refresh seems good.

**Comment by dbu** [comment]
so, 2.0 is near, so that would be a good time for behaviour changes.

one option i see is stop refreshing the phpcr layer and document that if you want to reset the phpcr level cache, you need to refresh the session. i would kind of like to rename the method so that people don't leave `clear` calls in their code without realizing that the semantics changed. but `clear` is the name also used in orm, and seems the best name for what we do.

@lsmith77 do you maybe have some input here?

**Comment by dantleech** [comment]
> i would kind of like to rename the method so that people don't leave clear calls in their code without realizing that the semantics change

I don't think `clear` suggests `reload from database`, so would rather keep that name than make a compromise. The break should be clearly documented and I expect most people will make a concious decision to updade to 2.0 unless they are depending on `dev-master`.

**Comment by pamil** [comment]
I'd vote for making this `clear()` method consistent with the ORM (it's the most expected behaviour IMO) and allow for refreshing session some other way (`$unitOfWork->refresh();` - making the parameter optional?).

**Pull request closed without merging**
