### PR TITLE
test with php 8

### PR DESCRIPTION
**Pull request by dbu**
depends on the whole phpcr and jackalope ecosystem allowing php 8...

### CODE REVIEW

**Comment by SenseException** [comment]
Is this still WIP?

**Comment by dbu** [comment]
@SenseException yes, look at the build error: some dependencies are not yet allowing php 8. 
i started on https://github.com/phpcr/phpcr-utils/pull/190 but now that one needs some adjustments for newer phpunit versions and i ran out of time. if you have time to have a look, that would help, otherwise i will try to look into it later this week.

**Comment by dbu** [comment]
the (hopefully) last blocker for this is https://github.com/jackalope/jackalope-doctrine-dbal/pull/373

**Comment by dbu** [comment]
i merged php 8 support into the 1.5 branch and released 1.5.3

updating master from 1.5 in https://github.com/doctrine/phpcr-odm/pull/819

**Pull request closed without merging**
