### PR TITLE
Import of the documentation for the new website

### PR DESCRIPTION
**Pull request by mikeSimonson**

### CODE REVIEW

**Comment by ElectricMaxxx** [comment]
Do we have a correlation on the version here now? Or do we start on master, so with the new 2.0?

**Comment by mikeSimonson** [comment]
I just put whatever was on master

**Comment by jwage** [comment]
@dbu Yes, we are working on a new website at new.doctrine-project.org and having all of the documentation standardized to be in the code repository makes things easier. Feel free to cleanup the current repo and then archive when you are ready.

**Comment by dbu** [comment]
great! doc in the same repo is so much easier to keep the doc in sync.

**Comment by dbu** [comment]
i updated the readme in https://github.com/doctrine/phpcr-odm-documentation but seem to not have admin rights on the repo, thus i can't archive it. can somebody with the right permissions put `[Archived] ` in front of the repo title and then set the whole repo to archived in the admin?

**Pull request merged**
