### PR TITLE
backport symfony 4.0 support to the 1.4 branch

### PR DESCRIPTION
**Pull request by dbu**
basically b8f750a6706fb4e5aed9db266db9d02d177f6a68

### CODE REVIEW

**Comment by dbu** [comment]
@tobion can you please check if things work as expected? if so, i will tag a new 1.4 version with this.

**Comment by Tobion** [comment]
LGTM. But I don't know the library that well.

**Comment by dbu** [comment]
@Tobion i meant: if things in FOSElasticaBundle work as expected (it installs symfony 4 with phpcr-odm and tests succeed)

**Comment by Tobion** [comment]
We will see when you tag it. I don't wanna change the minimum stability just fo this.

**Comment by dbu** [comment]
tagged

**Pull request merged**
