### PR TITLE
Removing license header

### PR DESCRIPTION
**Pull request by mikeSimonson**

### CODE REVIEW

**Comment by alcaeus** [comment]
@mikeSimonson can you fix StyleCI issues?

**Comment by dbu** [comment]
was this also done for the other doctrine repositories? i don't particularly care about the headers, so if we are legally fine with it lets ditch them.

**Comment by alcaeus** [comment]
Yes, Mike did this for pretty much every repo.

**Comment by mikeSimonson** [comment]
@alcaeus I will look at fixing styleCI and I still have a few repo to go to finish it all.

**Comment by dbu** [comment]
thanks!

**Pull request merged**
